name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Backend Image
      run: |
        docker build -f Dockerfile.backend -t ats-backend .
        docker tag ats-backend ${{ secrets.DOCKER_USERNAME }}/ats-backend:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/ats-backend:latest

    - name: Build and Push Frontend Image
      run: |
        docker build -f Dockerfile.frontend -t ats-frontend .
        docker tag ats-frontend ${{ secrets.DOCKER_USERNAME }}/ats-frontend:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/ats-frontend:latest
